"use client";

import { useCallback, useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { IconButton } from "@/components/ui/icon-button";
import { KanaStrokeReference } from "@/components/writing/kana-stroke-reference";
import { backingStoreSize, normalizeDrawingPoint, undoLastStroke } from "@/lib/drawing/model";
import type { DrawingLevel, DrawingStroke, KanaStrokeData } from "@/lib/drawing/types";

export interface KanaDrawingCanvasProps { data: KanaStrokeData; level: DrawingLevel; comparison?: boolean; onChange?: (strokes: readonly DrawingStroke[]) => void; }
export function KanaDrawingCanvas({ data, level, comparison = false, onChange }: KanaDrawingCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const strokesRef = useRef<DrawingStroke[]>([]); const activeStrokeRef = useRef<DrawingStroke | null>(null); const frameRef = useRef<number | null>(null);
  const [strokeCount, setStrokeCount] = useState(0); const [demonstrating, setDemonstrating] = useState(false);
  const renderStrokes = useCallback(() => {
    const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext("2d"); if (!context) return; const rect = canvas.getBoundingClientRect(); const backing = backingStoreSize(rect.width, rect.height, window.devicePixelRatio);
    if (canvas.width !== backing.width || canvas.height !== backing.height) { canvas.width = backing.width; canvas.height = backing.height; }
    context.setTransform(backing.ratio, 0, 0, backing.ratio, 0, 0); context.clearRect(0, 0, rect.width, rect.height); context.lineCap = "round"; context.lineJoin = "round"; context.lineWidth = Math.max(7, rect.width * 0.024); context.strokeStyle = "#171719";
    for (const stroke of strokesRef.current) { if (!stroke.points.length) continue; const points = stroke.points; context.beginPath(); context.moveTo(points[0].x * rect.width, points[0].y * rect.height); if (points.length === 1) context.lineTo(points[0].x * rect.width + 0.01, points[0].y * rect.height); else for (let index = 1; index < points.length; index += 1) { const previous = points[index - 1]; const point = points[index]; context.quadraticCurveTo(previous.x * rect.width, previous.y * rect.height, ((previous.x + point.x) / 2) * rect.width, ((previous.y + point.y) / 2) * rect.height); } context.stroke(); }
  }, []);
  const scheduleRender = useCallback(() => { if (frameRef.current !== null) return; frameRef.current = window.requestAnimationFrame(() => { frameRef.current = null; renderStrokes(); }); }, [renderStrokes]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; renderStrokes(); const observer = new ResizeObserver(renderStrokes); observer.observe(canvas); return () => { observer.disconnect(); if (frameRef.current !== null) window.cancelAnimationFrame(frameRef.current); }; }, [renderStrokes]);
  const pointsFromEvent = (event: ReactPointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const native = event.nativeEvent; const events = typeof native.getCoalescedEvents === "function" ? native.getCoalescedEvents() : [native]; return events.map((point) => normalizeDrawingPoint(point.clientX, point.clientY, rect, point.timeStamp, point.pressure)); };
  const startStroke = (event: ReactPointerEvent<HTMLCanvasElement>) => { if (demonstrating || comparison) return; event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); const stroke = { points: pointsFromEvent(event) }; activeStrokeRef.current = stroke; strokesRef.current = [...strokesRef.current, stroke]; scheduleRender(); };
  const continueStroke = (event: ReactPointerEvent<HTMLCanvasElement>) => { if (!activeStrokeRef.current) return; event.preventDefault(); activeStrokeRef.current.points.push(...pointsFromEvent(event)); scheduleRender(); };
  const finishStroke = (event: ReactPointerEvent<HTMLCanvasElement>) => { if (!activeStrokeRef.current) return; event.preventDefault(); activeStrokeRef.current = null; setStrokeCount(strokesRef.current.length); onChange?.(strokesRef.current); scheduleRender(); };
  const clear = () => { strokesRef.current = []; activeStrokeRef.current = null; setStrokeCount(0); onChange?.([]); scheduleRender(); };
  const undo = () => { strokesRef.current = undoLastStroke(strokesRef.current); activeStrokeRef.current = null; setStrokeCount(strokesRef.current.length); onChange?.(strokesRef.current); scheduleRender(); };
  const demonstrate = () => { clear(); setDemonstrating(true); };
  const showStaticReference = !demonstrating && (level === "trace" || comparison);
  return <div className="w-full"><div className="relative aspect-square w-full overflow-hidden rounded-[var(--radius-hero)] border border-[var(--border)] bg-white shadow-[0_18px_60px_rgba(55,21,143,.07)]"><div className="pointer-events-none absolute inset-0" aria-hidden="true"><span className="absolute inset-3 rounded-xl border border-[var(--nazumo-purple)]/10"/><span className="absolute left-1/2 top-3 bottom-3 w-px bg-[var(--nazumo-purple)]/10"/><span className="absolute left-3 right-3 top-1/2 h-px bg-[var(--nazumo-purple)]/10"/></div>{showStaticReference ? <KanaStrokeReference data={data} className={`pointer-events-none absolute inset-[7%] size-[86%] ${comparison ? "text-[var(--electric-violet)] opacity-55" : "text-[var(--nazumo-purple)] opacity-14"}`} showNumbers={level === "trace" && !comparison} /> : null}{demonstrating ? <KanaStrokeReference key={`demo-${data.character}`} data={data} animated showNumbers className="pointer-events-none absolute inset-[7%] size-[86%] text-[var(--nazumo-purple)]" /> : null}<canvas ref={canvasRef} onPointerDown={startStroke} onPointerMove={continueStroke} onPointerUp={finishStroke} onPointerCancel={finishStroke} className={`absolute inset-0 size-full touch-none ${demonstrating || comparison ? "pointer-events-none" : "cursor-crosshair"}`} role="img" aria-label={`Lienzo para escribir ${data.character}. ${strokeCount} trazos dibujados.`} /></div>
    <div className="mt-3 flex min-h-12 items-center justify-between gap-3"><span className="text-xs text-[var(--muted)]" aria-live="polite">{strokeCount} {strokeCount === 1 ? "trazo" : "trazos"}</span><div className="flex gap-2"><button type="button" onClick={demonstrate} disabled={demonstrating} className="min-h-12 rounded-[var(--radius-control)] bg-white px-4 text-sm font-bold text-[var(--nazumo-purple)] disabled:opacity-50">Ver trazos</button><IconButton icon="undo" label="Deshacer el último trazo" onClick={undo} disabled={strokeCount === 0 || demonstrating || comparison} className="bg-white text-[var(--sumi)] disabled:opacity-35" /><IconButton icon="trash" label="Borrar todos los trazos" onClick={clear} disabled={strokeCount === 0 || demonstrating || comparison} className="bg-white text-[var(--sumi)] disabled:opacity-35" /></div></div>
    {demonstrating ? <button type="button" onClick={() => setDemonstrating(false)} className="mt-3 min-h-12 w-full rounded-[var(--radius-button)] border border-[var(--border)] bg-white text-sm font-bold">Volver a intentarlo</button> : null}<span className="sr-only">{strokeCount > 0 ? "El lienzo contiene un dibujo" : "El lienzo está vacío"}</span></div>;
}
